output:
  output-img-path: ./output/img/img%04d.png
  output-audio-path: ./output/audio/audio.mp3
  output-video-path: ./output/video/video.mp4
  output-log-path: ./output/app.log
base-path:
  video-cover-img: ./resource/images/video_cover_img.png
  video-stop-img: ./resource/images/video_stop_img.png

