output:
  output-img-path: ./output/img/img%04d.png
  output-audio-path: ./output/audio/audio.mp3
  output-video-path: ./output/video/video.mp4
  output-log-path: ./output/app.log
base-path:
  video-cover-img: ./resource/images/video_cover_img.png
  video-stop-img: ./resource/images/video_stop_img.png


#   output-video-path: yourAccessKeySecret
#   output-log-path: yourBucketName
# aws-s3:
#   bucket: xxxxx-10005608
#   region: ap-shanghai
#   endpoint: ""
#   s3-force-path-style: false
#   disable-ssl: false
#   secret-id: your-secret-id
#   secret-key: your-secret-key
#   base-url: https://gin.vue.admin
#   path-prefix: github.com/flipped-aurora/gin-vue-admin/server
# captcha:
#   key-long: 6
#   img-width: 240
#   img-height: 80
# cors:
#   mode: strict-whitelist
#   whitelist:
#   - allow-origin: example1.com
#     allow-methods: POST, GET
#     allow-headers: Content-Type,AccessToken,X-CSRF-Token, Authorization, Token,X-Token,X-User-Id
#     expose-headers: Content-Length, Access-Control-Allow-Origin, Access-Control-Allow-Headers,
#       Content-Type
#     allow-credentials: true
#   - allow-origin: example2.com
#     allow-methods: GET, POST
#     allow-headers: content-type
#     expose-headers: Content-Length, Access-Control-Allow-Origin, Access-Control-Allow-Headers,
#       Content-Type
#     allow-credentials: true
# db-list:
# - disable: true
#   type: ""
#   alias-name: ""
#   path: ""
#   port: ""
#   config: ""
#   db-name: ""
#   username: ""
#   password: ""
#   prefix: ""
#   singular: false
#   engine: ""
#   max-idle-conns: 10
#   max-open-conns: 100
#   log-mode: ""
#   log-zap: false
# email:
#   to: 1256002974@qq.com
#   port: 465
#   from: www.404name@qq.com
#   host: smtp.qq.com
#   is-ssl: true
#   secret: rmcoaslbbkexjjhb
#   nickname: test
# excel:
#   dir: ./resource/excel/
# hua-wei-obs:
#   path: you-path
#   bucket: you-bucket
#   endpoint: you-endpoint
#   access-key: you-access-key
#   secret-key: you-secret-key
# jwt:
#   signing-key: 1a65cafd-7ea4-4799-ba37-59cda15b52fe
#   expires-time: 7d
#   buffer-time: 1d
#   issuer: qmPlus
# local:
#   path: uploads/file
#   store-path: uploads/file
# mysql:
#   path: hw.404name.top
#   port: "3306"
#   config: charset=utf8mb4&parseTime=True&loc=Local
#   db-name: gva
#   username: root
#   password: "13979933306"
#   prefix: ""
#   singular: false
#   engine: ""
#   max-idle-conns: 10
#   max-open-conns: 100
#   log-mode: error
#   log-zap: false
# oracle:
#   path: ""
#   port: ""
#   config: ""
#   db-name: ""
#   username: ""
#   password: ""
#   prefix: ""
#   singular: false
#   engine: ""
#   max-idle-conns: 0
#   max-open-conns: 0
#   log-mode: ""
#   log-zap: false
# pgsql:
#   path: ""
#   port: ""
#   config: ""
#   db-name: ""
#   username: ""
#   password: ""
#   prefix: ""
#   singular: false
#   engine: ""
#   max-idle-conns: 10
#   max-open-conns: 100
#   log-mode: ""
#   log-zap: false
# qiniu:
#   zone: ZoneHuaDong
#   bucket: ""
#   img-path: ""
#   use-https: false
#   access-key: ""
#   secret-key: ""
#   use-cdn-domains: false
# redis:
#   db: 0
#   addr: hw.404name.top:6379
#   password: "13979933306"
# system:
#   env: public
#   addr: 8888
#   db-type: mysql
#   oss-type: local
#   use-multipoint: false
#   use-redis: true
#   iplimit-count: 10
#   iplimit-time: 60
# tencent-cos:
#   bucket: xxxxx-10005608
#   region: ap-shanghai
#   secret-id: your-secret-id
#   secret-key: your-secret-key
#   base-url: https://gin.vue.admin
#   path-prefix: github.com/flipped-aurora/gin-vue-admin/server
# timer:
#   start: true
#   spec: '@daily'
#   with_seconds: false
#   detail:
#   - tableName: sys_operation_records
#     compareField: created_at
#     interval: 2160h
#   - tableName: jwt_blacklists
#     compareField: created_at
#     interval: 168h
# zap:
#   level: info
#   prefix: '[github.com/flipped-aurora/gin-vue-admin/server]'
#   format: console
#   director: log
#   encode-level: LowercaseColorLevelEncoder
#   stacktrace-key: stacktrace
#   max-age: 0
#   show-line: true
#   log-in-console: true
